//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfiniteScroll.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trek
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Difficulty { get; set; }
        public string Country { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> DifficultyLevel { get; set; }
    }
}
